# Generated by Django 3.1.4 on 2020-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='text',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
