# Generated by Django 3.1.4 on 2020-12-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in_clinic', '0003_auto_20201214_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='dr_email',
            field=models.EmailField(default='Dan', max_length=50),
        ),
        migrations.AddField(
            model_name='clinic',
            name='dr_phonenumber',
            field=models.IntegerField(default=5263648574, max_length=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='location',
            field=models.CharField(default='39 York Road, London, SW81 4AQ, England', max_length=50),
        ),
        migrations.AddField(
            model_name='clinic',
            name='payment_method_available',
            field=models.CharField(choices=[('pp', 'PayPal'), ('cc', 'Credit Card'), ('dc', 'Debit Card'), ('ca', 'Cash')], default=('cc', 'Credit Card'), max_length=2),
        ),
    ]
