# Generated by Django 3.1.4 on 2020-12-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in_clinic', '0004_auto_20201214_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='dr_phonenumber',
            field=models.IntegerField(default=5263648574),
        ),
    ]
